### ISSUE TITLE
[REQUEST] to be able to hide the white circle on objects

### ISSUE THREAD

**Issue by lewislepton** [Devination/VerletKha#3]
just to allow you to hide the white circle that shows that you can pick/move an object/entity

**Comment by Devination** [comment]
Added on the [Rendering Trello card](https://trello.com/c/OpHhNTF1/2-rendering)

**Comment by Devination** [comment]
Renderer.Instance.highlightNearest = false;

**Comment by lewislepton** [comment]
what can be done to even stop the dragging?

**Comment by lewislepton** [comment]
and thank you. works great ;)

**Comment by Devination** [comment]
> what can be done to even stop the dragging?

You can add this to your _khafile.js_:
`project.addDefine('noDragger');`

Sorry for the late reply, I haven't been getting email notifications about issues on this project.
