### ISSUE TITLE
[BUG] current release brings drawCircle error

### ISSUE THREAD

**Issue by lewislepton** [Devination/VerletKha#7]
really weird error i run into lately with recent update

```
/usr/local/lib/haxe/lib/verlet/git/Sources/verlet/Renderer.hx:47: characters 3-22 : kha.graphics2.Graphics has no field drawCircle
```

even from using code that had worked before

**Comment by estivate** [comment]
adding this line at the top of Renderer.hx fixes the error:

`using kha.graphics2.GraphicsExtension;`

**Comment by Devination** [comment]
Sorry about that, I must have removed it while I was working with the noDragger define. Should be fixed with latest now.
